# Generated by Django 5.0.1 on 2024-02-13 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cardlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=200)),
                (
                    "card_amount",
                    models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
                ),
                (
                    "card_classification",
                    models.CharField(
                        blank=True,
                        choices=[("Starter", "Starter"), ("Garnet", "Garnet")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Decklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("deck_plaintext", models.TextField()),
                ("runs", models.PositiveSmallIntegerField(default=100)),
                ("hand_size", models.PositiveSmallIntegerField(default=5)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Combolist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("combo", models.ManyToManyField(to="decklist.cardlist")),
                (
                    "deck_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decklist.decklist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cardlist",
            name="deck_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="decklist.decklist"
            ),
        ),
    ]
