# Generated by Django 4.2.5 on 2023-09-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decklist',
            old_name='deck_item',
            new_name='deck_plaintext',
        ),
        migrations.AlterField(
            model_name='decklist',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='decklist',
            name='deck_combo',
            field=models.JSONField(default=dict),
        ),
    ]
