# Generated by Django 4.2.5 on 2023-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0003_simulator_alter_decklist_deck_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decklist',
            name='data',
            field=models.TextField(),
        ),
    ]
