# Generated by Django 4.2.5 on 2023-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0008_alter_decklist_deck_combo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simulator',
        ),
        migrations.AddField(
            model_name='decklist',
            name='hand_size',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='decklist',
            name='runs',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
