# Generated by Django 4.2.5 on 2023-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decklist', '0009_delete_simulator_decklist_hand_size_decklist_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decklist',
            name='deck_combo',
            field=models.TextField(),
        ),
    ]
