# Generated by Django 4.1 on 2024-01-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0012_alter_decklist_deck_combo"),
    ]

    operations = [
        migrations.AddField(
            model_name="decklist",
            name="card_object",
            field=models.JSONField(default=dict),
        ),
    ]
