# Generated by Django 4.1 on 2024-01-10 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0013_decklist_card_object"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decklist",
            name="card_object",
        ),
    ]
