# Generated by Django 4.1 on 2024-01-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0014_remove_decklist_card_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cardlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=200)),
                ("card_amount", models.PositiveSmallIntegerField(default=3)),
                ("card_classification", models.CharField(max_length=200)),
                (
                    "deck_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decklist.decklist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Combolist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("combo", models.JSONField(default=dict)),
                (
                    "card_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="decklist.cardlist",
                    ),
                ),
            ],
        ),
    ]
