# Generated by Django 4.1 on 2024-01-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0015_cardlist_combolist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combolist",
            name="card_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="decklist.decklist"
            ),
        ),
    ]
