# Generated by Django 4.1 on 2024-01-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0016_alter_combolist_card_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="combolist",
            old_name="card_list",
            new_name="deck_list",
        ),
        migrations.AlterField(
            model_name="combolist",
            name="combo",
            field=models.JSONField(default=[]),
        ),
    ]
