# Generated by Django 4.1 on 2024-01-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0017_rename_card_list_combolist_deck_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combolist",
            name="combo",
            field=models.JSONField(default=dict),
        ),
    ]
