# Generated by Django 4.1 on 2024-01-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0019_remove_combolist_combo_alter_cardlist_card_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combolist",
            name="card_1",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="decklist.cardlist",
            ),
        ),
    ]
