# Generated by Django 4.1 on 2024-01-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0020_combolist_card_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="combolist",
            name="card_2",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_2",
                to="decklist.cardlist",
            ),
        ),
        migrations.AddField(
            model_name="combolist",
            name="card_3",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_3",
                to="decklist.cardlist",
            ),
        ),
        migrations.AddField(
            model_name="combolist",
            name="card_4",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_4",
                to="decklist.cardlist",
            ),
        ),
        migrations.AddField(
            model_name="combolist",
            name="card_5",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_5",
                to="decklist.cardlist",
            ),
        ),
        migrations.AddField(
            model_name="combolist",
            name="card_6",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_6",
                to="decklist.cardlist",
            ),
        ),
        migrations.AlterField(
            model_name="combolist",
            name="card_1",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_1",
                to="decklist.cardlist",
            ),
        ),
    ]
