# Generated by Django 4.1 on 2024-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "decklist",
            "0021_combolist_card_2_combolist_card_3_combolist_card_4_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="combolist",
            name="combo",
            field=models.CharField(default="", max_length=200),
        ),
    ]
