# Generated by Django 5.0.1 on 2024-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0022_combolist_combo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combolist",
            name="card_1",
        ),
        migrations.RemoveField(
            model_name="combolist",
            name="card_2",
        ),
        migrations.RemoveField(
            model_name="combolist",
            name="card_3",
        ),
        migrations.RemoveField(
            model_name="combolist",
            name="card_4",
        ),
        migrations.RemoveField(
            model_name="combolist",
            name="card_5",
        ),
        migrations.RemoveField(
            model_name="combolist",
            name="card_6",
        ),
        migrations.RemoveField(
            model_name="combolist",
            name="combo",
        ),
        migrations.AddField(
            model_name="combolist",
            name="combo",
            field=models.ManyToManyField(to="decklist.cardlist"),
        ),
    ]
