# Generated by Django 5.0.1 on 2024-01-21 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("decklist", "0023_remove_combolist_card_1_remove_combolist_card_2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decklist",
            name="data",
        ),
        migrations.RemoveField(
            model_name="decklist",
            name="deck_combo",
        ),
    ]
